name: app_center_uploader
description: Tool to upload basic
version: 0.1.0
publish_to: none


environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  functional_data: ^0.2.3
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  meta: ^1.1.7
  mockito: ^4.1.1
  sum_types: ^0.1.5+1

dev_dependencies:
  build_runner: ^1.7.1
  functional_data_generator: ^0.2.5
  test: ^1.9.1
