name: app_center_uploader
description: Tool to upload binary to appcenter
version: 0.1.0
publish_to: none


environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  functional_data: ^0.2.3
  http: ^0.12.0+2
  http_parser: ^3.1.3
  json_annotation: ^3.0.0
  meta: ^1.1.7
  sum_types: ^0.2.1
  yaml: ^2.2.0

dev_dependencies:
  build_runner: ^1.7.1
  dependency_validator: ^1.0.0
  functional_data_generator: ^0.2.5
  json_serializable: ^3.2.0
  mockito: ^4.1.1
  sum_types_generator: ^0.2.1
  test: ^1.9.1
